version: '2.1'
services:
  testsslsh:
    build:
       context: .
       dockerfile: Dockerfile
    image: testssl.sh  
    container_name: testssl.sh
    volumes:
      - "./myshare:/home/tmp"
    command:  --jsonfile "/home/tmp/testssloutput.json" "10.223.227.93:8443"
    healthcheck:
      test: "exit 0"
      #  to check every 1 min and 30 sec or so that the script is done within 5 minutes:
      interval: 1m30s
      timeout: 5m
      retries: 5
            
volumes:
  myshare:
    driver: local
